### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by AkshayGoelTech** [vthacks-iv/apply#1]
I think we can simply use typeform embedded into the HTML Website for Signups.
Thoughts?

**Comment by clcain** [comment]
Are you referring to changing the committee application or are you talking about what we should do for the general hackathon application?

**Comment by AkshayGoelTech** [comment]
General. Is that not what this repo is for?

If I'm wrong, please mark as resolved

**Comment by clcain** [comment]
This repo is for anything hosted on the apply.vthacks.com subdomain. So both. Yes, I agree that we can use an embedded Typeform for the general application.
